# Generated by Buildr 1.4.22, change to your liking

# Version number for this release
# VERSION_NUMBER = "1.0.0"
THIS_VERSION = "0.0.0-SNAPSHOT"
# Group identifier for your projects
GROUP = "dlc_final"
COPYRIGHT = ""

# Specify Maven 2.0 remote repositories here, like this:
repositories.remote << "http://repo1.maven.org/maven2"

# Requirements
MYSQL = 'mysql:mysql-connector-java:jar:5.1.34'
JAVAX_SERVLET = 'javax.servlet:javax.servlet-api:jar:3.0.1'

desc "The Dlc_final project"
define "dlc_final" do

  project.version = THIS_VERSION
  project.group = GROUP
  manifest["Implementation-Vendor"] = COPYRIGHT
  # test.compile.with # Add classpath dependencies

  desc 'Backend search engine'
  define 'backend' do
    compile.with MYSQL
    # package :jar
    package(:jar).with :manifest=>manifest.merge('Main-Class'=>'com.dlc.backend.Main')
  end

  desc 'Frontend AJAX web interface'
  define 'ajax-frontend' do
    compile.with JAVAX_SERVLET
    package :war
  end

end
