# Generated by Buildr 1.4.22, change to your liking

# Version number for this release
# VERSION_NUMBER = "1.0.0"
THIS_VERSION = "1.0.0"
# Group identifier for your projects
GROUP = "dlc_final"
COPYRIGHT = ""

# Specify Maven 2.0 remote repositories here, like this:
repositories.remote << "http://repo1.maven.org/maven2"
# repositories.remote << 'http://www.ibiblio.org/maven2/'
repositories.release_to = 'sftp://flor@ubuntu-vm/home/flor'

# Requirements
MYSQL = 'mysql:mysql-connector-java:jar:5.1.34'
JAVAX_SERVLET = 'javax.servlet:javax.servlet-api:jar:3.0.1'

# Main classes
backend_main = "com.dlc.backend.Main"

# Database Setup
DLC_DB = "dlc_db"
DLC_USER = "dlc"
DLC_PWD = "dlc"

# Custom tasks
Project.local_task :create_tables
Project.local_task :setup_db
Project.local_task :run_mock_server

desc "The Dlc_final project"
define "dlc_final" do

  project.version = THIS_VERSION
  project.group = GROUP
  manifest["Implementation-Vendor"] = COPYRIGHT

  desc 'Backend search engine'
  define 'backend' do
    compile.with MYSQL
    package(:jar).with :manifest=>manifest.merge('Main-Class'=>backend_main)
        # 'Class-Path'=>'lib/mysql-connector-java.jar')
  end

  desc 'Frontend AJAX web interface'
  define 'ajax-frontend' do
    compile.with JAVAX_SERVLET
    package :war
  end

  task :run => :package do
    project('backend').task("package")
    puts 'running...'
    # puts artifact(MYSQL).to_s
    # puts project('backend').package(:jar).to_s
    cmd = "java -Xdebug -classpath " + artifact(MYSQL).to_s + ":"
    cmd += project('backend').package(:jar).to_s +  " " + backend_main
    puts cmd
    system(cmd)
  end

  task :setup_db do
    create_user = "CREATE USER '%s'@'%s' IDENTIFIED BY '%s';\n"
    grant_user = "GRANT ALL PRIVILEGES ON %s.* TO '%s'@'%s' WITH GRANT OPTION;\n"

    cmd = "CREATE DATABASE %s;\n" % DLC_DB
    cmd += create_user % [DLC_USER, "localhost", DLC_PWD]
    cmd += grant_user % [DLC_DB, DLC_USER, "localhost"]
    cmd += create_user % [DLC_USER, "%", DLC_PWD]
    cmd += grant_user % [DLC_DB, DLC_USER, "%"]
    puts cmd
    system('echo "%s" | mysql --user=root -p mysql' % cmd)
  end

  task :create_tables do
    doc_table = "create table document(\n\t"\
        "id INT NOT NULL PRIMARY KEY,\n\t"\
        "document varchar(200) NOT NULL);\n"

    term_table = "create table term(\n\t"\
        "id INT NOT NULL PRIMARY KEY,\n\t"\
        "term varchar(50) NOT NULL);\n"

    post_table = "create table post(\n\t"\
        "term int NOT NULL,\n\t"\
        "document int NOT NULL,\n\t"\
        "freq int(11), \n\t"\
        "FOREIGN KEY (term) references term(id),\n\t"\
        "FOREIGN KEY (document) references document(id));\n"

    cmd = "drop table if exists post;\ndrop table if exists document;\ndrop table if exists term;\n"
    cmd += doc_table + term_table + post_table
    cmd += "drop table if exists nr;\ndrop table if exists maxtf; "
    puts cmd
    system('echo "%s" | mysql -u %s -p%s %s' % [cmd, DLC_USER, DLC_PWD, DLC_DB])
  end

end
